ruby/config/routes.rb
Interview::Application.routes.draw do

  root :to => 'welcome#index'

  resources :hotels
  resources :members
  resources :hotel_stays
  resources :hotel_reviews

end

ruby/app/models/hotel.rb
class Hotel < ActiveRecord::Base

  attr_accessible :name

  has_many :hotel_stays
  has_many :hotel_reviews

  validates :name, presence: true, uniqueness: true

end

ruby/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hotels }
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/new
  # GET /hotels/new.json
  def new
    @hotel = Hotel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/1/edit
  def edit
    @hotel = Hotel.find(params[:id])
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(params[:hotel])

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render json: @hotel, status: :created, location: @hotel }
      else
        format.html { render action: "new" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hotels/1
  # PUT /hotels/1.json
  def update
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      if @hotel.update_attributes(params[:hotel])
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url }
      format.json { head :no_content }
    end
  end
end

ruby/app/helpers/hotels_helper.rb
module HotelsHelper
end

ruby/app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

ruby/app/views/hotels/index.html.erb
<h1>Listing hotels</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hotels.each do |hotel| %>
  <tr>
    <td><%= hotel.name %></td>
    <td><%= link_to 'Show', hotel %></td>
    <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
    <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hotel', new_hotel_path %>

ruby/app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

ruby/app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hotel.name %>
</p>


<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>