ruby/config/routes.rb
Interview::Application.routes.draw do

  root :to => 'welcome#index'

  resources :hotels
  resources :members
  resources :hotel_stays
  resources :hotel_reviews

end

ruby/app/controllers/hotel_reviews_controller.rb
class HotelReviewsController < ApplicationController
  # GET /hotel_reviews
  # GET /hotel_reviews.json
  def index
    @hotel_reviews = HotelReview.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hotel_reviews }
    end
  end

  # GET /hotel_reviews/1
  # GET /hotel_reviews/1.json
  def show
    @hotel_review = HotelReview.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hotel_review }
    end
  end

  # GET /hotel_reviews/new
  # GET /hotel_reviews/new.json
  def new
    @hotel_review = HotelReview.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hotel_review }
    end
  end

  # GET /hotel_reviews/1/edit
  def edit
    @hotel_review = HotelReview.find(params[:id])
  end

  # POST /hotel_reviews
  # POST /hotel_reviews.json
  def create
    @hotel_review = HotelReview.new(params[:hotel_review])

    respond_to do |format|
      if @hotel_review.save
        format.html { redirect_to @hotel_review, notice: 'Hotel review was successfully created.' }
        format.json { render json: @hotel_review, status: :created, location: @hotel_review }
      else
        format.html { render action: "new" }
        format.json { render json: @hotel_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hotel_reviews/1
  # PUT /hotel_reviews/1.json
  def update
    @hotel_review = HotelReview.find(params[:id])

    respond_to do |format|
      if @hotel_review.update_attributes(params[:hotel_review])
        format.html { redirect_to @hotel_review, notice: 'Hotel review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hotel_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotel_reviews/1
  # DELETE /hotel_reviews/1.json
  def destroy
    @hotel_review = HotelReview.find(params[:id])
    @hotel_review.destroy

    respond_to do |format|
      format.html { redirect_to hotel_reviews_url }
      format.json { head :no_content }
    end
  end
end

ruby/app/helpers/hotel_reviews_helper.rb
module HotelReviewsHelper
end

ruby/app/views/hotel_reviews/_form.html.erb
<%= form_for(@hotel_review) do |f| %>
  <% if @hotel_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel_review.errors.count, "error") %> prohibited this hotel_review from being saved:</h2>

      <ul>
      <% @hotel_review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hotel_id %><br />
    <%= f.select :hotel_id, options_for_select(Hotel.all.collect { |h| [ h.name, h.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.select :member_id, options_for_select(Member.all.collect { |h| [ h.name, h.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/app/views/hotel_reviews/edit.html.erb
<h1>Editing hotel review</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel_review %> |
<%= link_to 'Back', hotel_reviews_path %>

ruby/app/views/hotel_reviews/index.html.erb
<h1>Listing hotel reviews</h1>

<table>
  <tr>
    <th>Hotel</th>
    <th>Member</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hotel_reviews.each do |hotel_review| %>
  <tr>
    <td><%= hotel_review.hotel.name %></td>
    <td><%= hotel_review.member.name %></td>
    <td><%= hotel_review.score %></td>
    <td><%= link_to 'Show', hotel_review %></td>
    <td><%= link_to 'Edit', edit_hotel_review_path(hotel_review) %></td>
    <td><%= link_to 'Destroy', hotel_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hotel review', new_hotel_review_path %>

ruby/app/views/hotel_reviews/new.html.erb
<h1>New hotel review</h1>

<%= render 'form' %>

<%= link_to 'Back', hotel_reviews_path %>

ruby/app/views/hotel_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hotel:</b>
  <%= @hotel_review.hotel.name %>
</p>

<p>
  <b>Member:</b>
  <%= @hotel_review.member.name %>
</p>

<p>
  <b>Score:</b>
  <%= @hotel_review.score %>
</p>


<%= link_to 'Edit', edit_hotel_review_path(@hotel_review) %> |
<%= link_to 'Back', hotel_reviews_path %>