ruby/config/routes.rb
Interview::Application.routes.draw do

  root :to => 'welcome#index'

  resources :hotels
  resources :members
  resources :hotel_stays
  resources :hotel_reviews

end

ruby/app/models/hotel_stay.rb
class HotelStay < ActiveRecord::Base

  attr_accessible :checkout_at, :hotel_id, :member_id

  belongs_to :hotel
  belongs_to :member

  validates :hotel, presence: true
  validates :member, presence: true
  validates :checkout_at, inclusion: { in: (Date.civil(2010, 5, 19))..(Date.today) }

end

ruby/app/controllers/hotel_stays_controller.rb
class HotelStaysController < ApplicationController
  # GET /hotel_stays
  # GET /hotel_stays.json
  def index
    @hotel_stays = HotelStay.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hotel_stays }
    end
  end

  # GET /hotel_stays/1
  # GET /hotel_stays/1.json
  def show
    @hotel_stay = HotelStay.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hotel_stay }
    end
  end

  # GET /hotel_stays/new
  # GET /hotel_stays/new.json
  def new
    @hotel_stay = HotelStay.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hotel_stay }
    end
  end

  # GET /hotel_stays/1/edit
  def edit
    @hotel_stay = HotelStay.find(params[:id])
  end

  # POST /hotel_stays
  # POST /hotel_stays.json
  def create
    @hotel_stay = HotelStay.new(params[:hotel_stay])

    respond_to do |format|
      if @hotel_stay.save
        format.html { redirect_to @hotel_stay, notice: 'Hotel stay was successfully created.' }
        format.json { render json: @hotel_stay, status: :created, location: @hotel_stay }
      else
        format.html { render action: "new" }
        format.json { render json: @hotel_stay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hotel_stays/1
  # PUT /hotel_stays/1.json
  def update
    @hotel_stay = HotelStay.find(params[:id])

    respond_to do |format|
      if @hotel_stay.update_attributes(params[:hotel_stay])
        format.html { redirect_to @hotel_stay, notice: 'Hotel stay was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hotel_stay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotel_stays/1
  # DELETE /hotel_stays/1.json
  def destroy
    @hotel_stay = HotelStay.find(params[:id])
    @hotel_stay.destroy

    respond_to do |format|
      format.html { redirect_to hotel_stays_url }
      format.json { head :no_content }
    end
  end
end

ruby/app/helpers/hotel_stays_helper.rb
module HotelStaysHelper
end

ruby/app/views/hotel_stays/_form.html.erb
<%= form_for(@hotel_stay) do |f| %>
  <% if @hotel_stay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel_stay.errors.count, "error") %> prohibited this hotel_stay from being saved:</h2>

      <ul>
      <% @hotel_stay.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hotel_id %><br />
    <%= f.select :hotel_id, options_for_select(Hotel.all.collect { |h| [ h.name, h.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.select :member_id, options_for_select(Member.all.collect { |h| [ h.name, h.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :checkout_at %><br />
    <%= f.date_select :checkout_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/app/views/hotel_stays/edit.html.erb
<h1>Editing hotel stay</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel_stay %> |
<%= link_to 'Back', hotel_stays_path %>

ruby/app/views/hotel_stays/index.html.erb
<h1>Listing hotel stays</h1>

<table>
  <tr>
    <th>Hotel</th>
    <th>Member</th>
    <th>Checkout at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hotel_stays.each do |hotel_stay| %>
  <tr>
    <td><%= hotel_stay.hotel.name %></td>
    <td><%= hotel_stay.member.name %></td>
    <td><%= hotel_stay.checkout_at %></td>
    <td><%= link_to 'Show', hotel_stay %></td>
    <td><%= link_to 'Edit', edit_hotel_stay_path(hotel_stay) %></td>
    <td><%= link_to 'Destroy', hotel_stay, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hotel stay', new_hotel_stay_path %>

ruby/app/views/hotel_stays/new.html.erb
<h1>New hotel stay</h1>

<%= render 'form' %>

<%= link_to 'Back', hotel_stays_path %>

ruby/app/views/hotel_stays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hotel:</b>
  <%= @hotel_stay.hotel.name %>
</p>

<p>
  <b>Member:</b>
  <%= @hotel_stay.member.name %>
</p>

<p>
  <b>Checkout at:</b>
  <%= @hotel_stay.checkout_at %>
</p>


<%= link_to 'Edit', edit_hotel_stay_path(@hotel_stay) %> |
<%= link_to 'Back', hotel_stays_path %>